# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/xdc/con-fmc_lpc_zed.xdc

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/xdc/fpga_etc.xdc

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/xdc/fpga_zed.xdc

# Block Designs: bd/design_riscv_cache/design_riscv_cache.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache || ORIG_REF_NAME==design_riscv_cache} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_axi_bram_ctrl_0_0/design_riscv_cache_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_riscv_cache_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_axi_bram_ctrl_0_bram_0/design_riscv_cache_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_riscv_cache_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_bfm_axi_if_0_0/design_riscv_cache_bfm_axi_if_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_bfm_axi_if_0_0 || ORIG_REF_NAME==design_riscv_cache_bfm_axi_if_0_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_clk_wiz_0_0/design_riscv_cache_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_clk_wiz_0_0 || ORIG_REF_NAME==design_riscv_cache_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_proc_sys_reset_0_0/design_riscv_cache_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_proc_sys_reset_0_0 || ORIG_REF_NAME==design_riscv_cache_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_riscv_cache_soc_0_0/design_riscv_cache_riscv_cache_soc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_riscv_cache_soc_0_0 || ORIG_REF_NAME==design_riscv_cache_riscv_cache_soc_0_0} -quiet] -quiet

# IP: bd/design_riscv_cache/ip/design_riscv_cache_rstmgra_0_0/design_riscv_cache_rstmgra_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_riscv_cache_rstmgra_0_0 || ORIG_REF_NAME==design_riscv_cache_rstmgra_0_0} -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/project_design_riscv_cache/project_design_riscv_cache.gen/sources_1/bd/design_riscv_cache/design_riscv_cache_ooc.xdc
