set_property SRC_FILE_INFO {cfile:/home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/xdc/fpga_zed.xdc rfile:../../../../xdc/fpga_zed.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports BOARD_CLK_IN]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports BOARD_RST_SW]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -reset_path -from [get_ports BOARD_RST_SW]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports uart_cts_n]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y10 [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA9 [get_ports uart_rts_n]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports {gpio_out[0]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T21 [get_ports {gpio_out[1]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U22 [get_ports {gpio_out[2]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21 [get_ports {gpio_out[3]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22 [get_ports {gpio_out[4]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports {gpio_out[5]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19 [get_ports {gpio_out[6]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports {gpio_out[7]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {gpio_in[0]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports {gpio_in[1]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22 [get_ports {gpio_in[2]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F21 [get_ports {gpio_in[3]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {gpio_in[4]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {gpio_in[5]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports {gpio_in[6]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {gpio_in[7]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {keypad_col[3]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {keypad_col[2]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {keypad_col[1]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {keypad_col[0]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {keypad_row[3]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {keypad_row[2]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {keypad_row[1]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {keypad_row[0]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V10 [get_ports i2c_sda]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports i2c_scl]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_riscv_cache_i/clk_wiz_0/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arburst[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arburst[1]}]]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wdata[31]}]]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arlen[7]}]]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_araddr[31]}]]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awsize[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awsize[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awsize[2]}]]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wdata[31]}]]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rresp[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rresp[1]}]]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rid[3]}]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wstrb[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wstrb[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wstrb[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wstrb[3]}]]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awlen[7]}]]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awaddr[31]}]]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bid[3]}]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bresp[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bresp[1]}]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arsize[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arsize[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arsize[2]}]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awid[3]}]]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awburst[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awburst[1]}]]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wstrb[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wstrb[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wstrb[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wstrb[3]}]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arsize[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arsize[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arsize[2]}]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rdata[31]}]]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awid[3]}]]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arburst[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arburst[1]}]]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bresp[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bresp[1]}]]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arid[3]}]]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awburst[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awburst[1]}]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bid[3]}]]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awlen[7]}]]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arid[3]}]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rid[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rid[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rid[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rid[3]}]]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awsize[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awsize[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awsize[2]}]]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awaddr[31]}]]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arlen[7]}]]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rresp[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rresp[1]}]]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_araddr[31]}]]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[7]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[8]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[9]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[10]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[11]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[12]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[13]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[14]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[15]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[16]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[17]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[18]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[19]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[20]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[21]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[22]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[23]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[24]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[25]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[26]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[27]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[28]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[29]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[30]} {design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rdata[31]}]]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_out[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_out[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_out[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_out[7]}]]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/keypad_col[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/keypad_col[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/keypad_col[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/keypad_col[3]}]]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_in[7]}]]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[2]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[3]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[4]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[5]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[6]} {design_riscv_cache_i/riscv_cache_soc_0/inst/gpio_dir[7]}]]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_tx/state[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_tx/state[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_tx/state[2]}]]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_rx/state[0]} {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_rx/state[1]} {design_riscv_cache_i/riscv_cache_soc_0/inst/u_uart/u_core/u_rx/state[2]}]]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_aresetn]]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arready]]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_arvalid]]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awready]]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe44 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_awvalid]]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bready]]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_bvalid]]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rlast]]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe48 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rready]]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe49 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_rvalid]]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe50 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wlast]]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe51 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wready]]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe52 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_data_wvalid]]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe53 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arready]]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe54 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_arvalid]]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe55 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awready]]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe56 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_awvalid]]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe57 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bready]]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe58 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_bvalid]]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe59 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rlast]]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe60 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rready]]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe61 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_rvalid]]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe62 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wlast]]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe63 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wready]]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe64 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/axi_inst_wvalid]]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe65 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/cpu_resetn]]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe66 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/i2c_scl]]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe67 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/i2c_sda]]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe68 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/uart_cts_n]]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe69 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/uart_rts_n]]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe70]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe70]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe70 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/uart_rxd]]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe71]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe71]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe71 [get_nets [list design_riscv_cache_i/riscv_cache_soc_0/inst/uart_txd]]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]
