# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.srcs/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0.xci
# IP: The module: 'design_gpio_axi_lite_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.srcs/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0.xci
# IP: The module: 'design_gpio_axi_lite_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_axi_lite_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
