# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-149521-sogang-500TGA-500SGA/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi4_to_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/i2c_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/pic_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/timer_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/uart_axi_lite/rtl/verilog
  } {
      /tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi4_to_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/i2c_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/pic_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/timer_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/uart_axi_lite/rtl/verilog
  } {
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/syn_define.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi_lite/rtl/verilog/amba_axi_lite_m5.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi4_to_lite/rtl/verilog/axi4_to_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi_switch/rtl/verilog/axi_switch_m3s3.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_axi.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_axi_axi.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_core.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_core_data_ram.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_core_tag_ram.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_if_pmem.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_mux.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/dcache_pmem_mux.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/rtl/verilog/gpio_axi_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/i2c_axi_lite/rtl/verilog/i2c_axi_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/icache.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/icache_data_ram.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/top_cache_axi/src_v/icache_tag_ram.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/mem_axi/rtl/verilog/mem_axi.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/pic_axi_lite/rtl/verilog/pic_axi_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_alu.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/hw/rtl/verilog/riscv_cache_core.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_core.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_csr.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_csr_regfile.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_decode.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_decoder.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_divider.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_exec.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_fetch.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_issue.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_lsu.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_mmu.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_multiplier.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_pipe_ctrl.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_regfile.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv/riscv_xilinx_2r1w.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/timer_axi_lite/rtl/verilog/timer_axi_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/uart_axi_lite/rtl/verilog/uart_axi_lite.v
      /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/hw/rtl/verilog/riscv_cache_soc.v
    }
      rt::read_verilog -include {
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/axi4_to_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/i2c_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/pic_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/riscv/core/riscv
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/timer_axi_lite/rtl/verilog
    /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/ips/uart_axi_lite/rtl/verilog
  } /home/sogang/pjt/team2/codes/riscv_platform/riscv32im_soc/hw/impl.ip_integrator/zed.confmc/project_design_riscv_cache/project_design_riscv_cache.gen/sources_1/bd/design_riscv_cache/ip/design_riscv_cache_riscv_cache_soc_0_0/synth/design_riscv_cache_riscv_cache_soc_0_0.v
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_riscv_cache_riscv_cache_soc_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-149521-sogang-500TGA-500SGA/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
