# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/xdc/con-fmc_lpc_zed.xdc

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/xdc/fpga_etc.xdc

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/xdc/fpga_zed.xdc

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/xdc/fpga_zed_sw_led.xdc

# Block Designs: bd/design_gpio_axi_lite/design_gpio_axi_lite.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite || ORIG_REF_NAME==design_gpio_axi_lite} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_axi4_to_lite_0_0/design_gpio_axi_lite_axi4_to_lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_axi4_to_lite_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_axi4_to_lite_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_bfm_axi_if_0_0/design_gpio_axi_lite_bfm_axi_if_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_bfm_axi_if_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_bfm_axi_if_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_clk_wiz_0_0/design_gpio_axi_lite_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_clk_wiz_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_gpio_axi_lite_0_0/design_gpio_axi_lite_gpio_axi_lite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_gpio_axi_lite_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_gpio_axi_lite_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_proc_sys_reset_0_0/design_gpio_axi_lite_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_proc_sys_reset_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_xlconcat_0_0/design_gpio_axi_lite_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_xlconcat_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_xlslice_0_0/design_gpio_axi_lite_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_xlslice_0_0 || ORIG_REF_NAME==design_gpio_axi_lite_xlslice_0_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_xlslice_1_0/design_gpio_axi_lite_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_xlslice_1_0 || ORIG_REF_NAME==design_gpio_axi_lite_xlslice_1_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_xlslice_2_0/design_gpio_axi_lite_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_xlslice_2_0 || ORIG_REF_NAME==design_gpio_axi_lite_xlslice_2_0} -quiet] -quiet

# IP: bd/design_gpio_axi_lite/ip/design_gpio_axi_lite_xlslice_3_0/design_gpio_axi_lite_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_gpio_axi_lite_xlslice_3_0 || ORIG_REF_NAME==design_gpio_axi_lite_xlslice_3_0} -quiet] -quiet

# XDC: /home/sogang/pjt/work/codes/riscv_platform/riscv32im_soc/ips/gpio_axi_lite/impl.zed/project_design_gpio_axi_lite/project_design_gpio_axi_lite.gen/sources_1/bd/design_gpio_axi_lite/design_gpio_axi_lite_ooc.xdc
